version: "3.7"

services:
  db_ignite:
    image: postgres
    container_name: rentx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentxdb
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx_app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
