version: "3.7"

services:
  db_ignite:
    image: postgres
    container_name: rentxDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentxdb
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-network

  app:
    # build: .
    image: rentx
    container_name: rentxApp
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
